# ARMS (tested with fc = 0.7)

A0353: # shoulder_yaw_1
  J: 0.25226729564112343
  f0: 4.116558516715117
  f1: 5.348034655365128
  f3: -0.13603002857940663
  k0: 0.8313211309421619
  k1: -1.262397729403924e-05
  k2: 1.1526854107656614e-10
  tau0: -1.056500738223606
  gain: 0.6

A0310: # shoulder_pitch_1
  J: 0.4278860156512358
  f0: 3.8632528052186212
  f1: 3.50464266935537
  f3: -0.04554965095398727
  k0: 0.920862886272313
  k1: -2.8666688414175352e-05
  k2: 4.331610454519371e-09
  tau0: -0.9288536245016279
  gain: 0.8

A0354: # elbow_pitch_1
  J: 0.28740484663968363
  f0: 3.987879032291721
  f1: 5.847763980620681
  f3: -0.13071444709387015
  k0: 0.8385022207898676
  k1: -2.132078701812127e-05
  k2: 2.9749020490196706e-10
  tau0: -1.2024931593098578
  gain: 0.4

A0361: # wrist_pitch_1
  J: 0.07865212501160687
  f0: 1.060453760302259
  f1: 0.7007520717418916
  f3: -0.004148691274120072
  k0: 1.2815990126825714
  k1: -0.005185780597391396
  k2: 1.783628018771947e-05
  tau0: 2.7021233418854265
  gain: 0.4

A0363: # wrist_yaw_1
  J: 0.07446068138726726
  f0: 0.9609157887432849
  f1: 0.7534196817465805
  f3: -0.004220145301316038
  k0: 1.2977512617822846
  k1: -0.0060833142741065875
  k2: 2.193537749416644e-05
  tau0: 2.9623345446951186
  gain: 0.5

A0352: # shoulder_yaw_2
  J: 0.30027579994742315
  f0: 3.839057031642698
  f1: 5.773140457206717
  f3: -0.15915207622354885
  k0: 0.8971028442315863
  k1: -2.3924419282812408e-05
  k2: 3.202340156950043e-10
  tau0: -1.1572204677753917
  gain: 0.6

A0309: # shoulder_pitch_2
  J: 0.45771190575310416
  f0: 2.2475537488475035
  f1: 4.4680573416383
  f3: -0.17203943212154077
  k0: 0.9820339204824784
  k1: -2.264479865588848e-05
  k2: 1.7349193912222175e-09
  tau0: -0.7825606896067127
  gain: 0.8

A0355: # elbow_pitch_2
  J: 0.34059126273773493
  f0: 3.001821131679829
  f1: 6.857368737457418
  f3: -0.20996981226323053
  k0: 0.9477344449328526
  k1: -2.19562874592868e-05
  k2: 2.5754443877553385e-10
  tau0: -1.6617023832175721
  gain: 0.4

A0362: # wrist_pitch_2
  J: 0.07621511814290363
  f0: 1.0759822042733584
  f1: 0.8049057270292118
  f3: -0.00305331243758722
  k0: 1.2364785195596362
  k1: -0.004627181457818813
  k2: 1.6051903207553375e-05
  tau0: 2.34214252716391
  gain: 0.5

A0327:  # wrist_yaw_2
  J: 0.07817304771289489
  f0: 1.2612576281195282
  f1: 0.7364753756819291
  f3: -0.004233586626073075
  k0: 1.3508319905655293
  k1: -0.005807833374248025
  k2: 2.022392475365572e-05
  tau0: 1.0901738436242459
  gain: 0.6

# LEGS
A0339:  # hip_pitch_1
  J: 0.19863795256439762
  f0: 3.821048078695134
  f1: 1.1807723055915944
  f3: -0.00831640451131396
  k0: 0.8487451556303667
  k1: -1.3808667148237898e-05
  k2: 1.4031907196332979e-10
  tau0: -0.4788543085795518
  gain: 0.5

A0340:  # hip_pitch_2
  J: 0.19107572300608058
  f0: 4.198267027506176
  f1: 0.8562600126437868
  f3: -0.0028120023508726825
  k0: 0.8130872615612934
  k1: -1.2847567767195618e-05
  k2: 1.411088596080191e-10
  tau0: -0.9001603868884811
  gain: 0.55

A0341:  # hip_pitch_3
  J: 0.19217026865968803
  f0: 3.9419311552311185
  f1: 0.9293563780451316
  f3: -0.0015197659520882068
  k0: 0.835771482274238
  k1: -1.4713191227769438e-05
  k2: 1.746147370438367e-10
  tau0: 0.2291878382913922
  gain: 0.75

A0342:  # hip_pitch_4
  J: 0.19894460053425306
  f0: 4.28935373710566
  f1: 0.8792809771475176
  f3: -0.0058174254025058145
  k0: 0.8524517402282127
  k1: -1.4191058231163425e-05
  k2: 1.585765214405723e-10
  tau0: -0.3533265452177764
  gain: 0.65

A0335:  # hip_roll_1
  J: 0.1896059630137304
  f0: 4.769295400825212
  f1: 0.7803754331785984
  f3: -0.0038496401695946748
  k0: 0.8193032066389179
  k1: -1.1946251416512394e-05
  k2: 1.0753598345188937e-10
  tau0: -0.46652262944902045
  gain: 0.5

A0336:  # hip_roll_2
  J: 0.195953996693805
  f0: 3.888458544178538
  f1: 1.0385419711546566
  f3: -0.008741692291535836
  k0: 0.8399703785162801
  k1: -1.4130327697837233e-05
  k2: 1.569831163198747e-10
  tau0: 0.06608200312282354
  gain: 0.5

A0337:  # hip_roll_3
  J: 0.2020795695429988
  f0: 3.5984246010181997
  f1: 1.162891915865523
  f3: -0.008867275317114526
  k0: 0.8660030541280342
  k1: -1.511275152950414e-05
  k2: 1.7093465568323648e-10
  tau0: -1.4210238694245954
  gain: 0.5

A0338:  # hip_roll_4
  J: 0.19452346801697407
  f0: 3.818480685802036
  f1: 1.1700758614529754
  f3: -0.009414471044126895
  k0: 0.8064495916988197
  k1: -1.2580219422162157e-05
  k2: 1.3310979333783413e-10
  tau0: -2.4716349606724988
  gain: 0.55

A0343:  # knee_pitch_1
  J: 0.1832222024699661
  f0: 5.010930684584346
  f1: 0.8967122217421455
  f3: -0.0011592272380415288
  k0: 0.779032775723322
  k1: -1.1067434913505365e-05
  k2: 1.1107092174376336e-10
  tau0: -0.560437312864788
  gain: 0.6

A0344:  # knee_pitch_2
  J: 0.19569892462167493
  f0: 4.571930500462324
  f1: 1.316966785145695
  f3: -0.010408964030408124
  k0: 0.8270859958599338
  k1: -1.2789488287374092e-05
  k2: 1.3016431426978275e-10
  tau0: -0.8747698119127386
  gain: 0.65

A0345:  # knee_pitch_3
  J: 0.19002989976115076
  f0: 4.157381329228115
  f1: 1.0426894396539783
  f3: -0.006006449309195814
  k0: 0.8159663885326321
  k1: -1.2897237218341921e-05
  k2: 1.2957093608668214e-10
  tau0: -0.5977901597601645
  gain: 0.65

A0346:  # knee_pitch_4
  J: 0.18741163841944744
  f0: 4.086168453935777
  f1: 1.0480281359846446
  f3: -0.006723868111579271
  k0: 0.8143604307141445
  k1: -1.1267163154748056e-05
  k2: 1.0104643157767186e-10
  tau0: -0.3581360868323339
  gain: 0.70