services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_IP=${ROS_IP}
    stdin_open: true
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    network_mode: host
    cap_add:
      - ALL
    restart: no
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/user/.ssh  # ssh
      # Mount the kyon_config repository root into the container
      - ../../:/home/user/xbot2_ws/src/kyon_config:ro
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https
      - ROBOT_CONFIG_PATH=/home/user/xbot2_ws/src/kyon_config/setup.sh

  dev:
    extends: base 
    volumes:
      - ~/.cache/kyon-cetc-noble-ros2-dev:/home/user/data
    environment:
      - CUSTOM_PS=(dev)


  dev-nvidia:
    extends: dev
    restart: always
    volumes:
      - ~:/home/user/host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1


  xbot2_gui_server:
    extends: base
    entrypoint: bash -ic "cd ~/xbot2_ws/src/kyon_config; git pull origin master; xbot2_gui_server gui/ros2/gui_server_config.yaml; bash"
    restart: always
    environment:
      - CUSTOM_PS=(xbot2_gui_server)
